experiments:
  - name: "Extensible_Mining_Experiment"
    dataset: "data/retail.txt"
    algorithms:
      - className: "core.algorithms.AprioriWrapper"
        parameters:
          minSupport: 0.1
      - className: "core.algorithms.FPGrowthWrapper"
        parameters:
          minSupport: 0.1
      - className: "core.algorithms.EclatWrapper"
        parameters:
          minSupport: 0.1